//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : WFElement.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.WorkflowEngine;


public class WFElement {
	public ActivityFactory factory;
	public void getData() {
	
	}
}
