//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : WFRunner.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.WorkflowEngine;

import java.util.ArrayList;


public class WFRunner implements IReturnEvent {
	private ArrayList<WFElement> elements;
	public EventNotifier eventNotifier;
	private void processElement(WFElement nextElem) {
	
	}
	
	private void start() {
	
	}
	
	private void end() {
	
	}
	
	public void sendICall() {
	
	}
	
	public void returnValueHandler(int result) {
	
	}
}
