//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : FileHandler.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class FileHandler {
	public void loadGCML(){
	}
	public void saveWXCML(){
	}
}
