//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Parser.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class Parser {
	public void createObjectModel(){
	}
}
