//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : PipeStream.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class PipeStream {
	public void setInputBuffer(){
	}
	public void setOutputBuffer(){
	}
}
