//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : ActivityFactory.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

namespace RRComSSys.WorkflowEngine
{
    public abstract class ActivityFactory : IActivityCreator
    {
        #region Implementation of IActivityCreator

        public abstract IActivity createActvity();

        #endregion
    }
}