//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Boundary.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

namespace RRComSSys.WorkflowEngine
{
    public class Boundary : IActivity
    {
        #region Implementation of IActivity

        public bool processActivity()
        {
            return true;
        }

        #endregion
    }
}
