//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Boundary.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


public class Boundary : IActivity{
}
