//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : CallFactory.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


public class CallFactory : ActivityFactory{
}
