//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : CallFactory.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


using RRComSSys.WorkflowEngine;

namespace RRComSSys.WorkflowEngine
{
    public class CallFactory : ActivityFactory
    {
        #region Overrides of ActivityFactory

        public override IActivity createActvity()
        {
            throw new System.NotImplementedException();
        }

        #endregion
    }
}
