//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : IActivity.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//
namespace RRComSSys.WorkflowEngine
{
    public interface IActivity {
        bool processActivity();
    }
}