//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WFElement.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class WFElement {
	public ActivityFactory factory ;
	public void getData(){
	}
}
