//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WFElement.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//
namespace RRComSSys.WorkflowEngine
{
    public class WFElement
    {
        public ActivityFactory factory;
        public void getData()
        {
        }
    }
}

