
//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WFRunner.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


using System.Collections.Generic;
using RRComSSys.WorkflowEngine;

namespace RRComSSys.WorkflowEngine
{
    internal class WFRunner : IReturnEvent
    {
        private List<WFElement> elements = null;

        public List<WFElement> WorkflowElements
        {
            get
            {
                if (null == elements)
                  WorkflowElements = new List<WFElement>();

                return elements;
            }
            private set
            {
                elements = value;
            }
        }

        public WFRunner()
        {
        }

        public EventNotifier eventNotifier;
        
        public bool ExecuteWorkflow()
        {
            Boundary start = Start();
            WFElement element = elements.Find(x => x.getActivityID().Equals(start.nextActivityID()));
            processElement(element);
            return true;
        }

        private void processElement(WFElement nextElem)
        {

        }

        private Boundary Start()
        {
            Boundary start = (Boundary) elements.Find(x=> ((x.TypeOfActivity() == typeof(Boundary)) && ((Boundary)x).Starts()));
            return start;
        }

        private void end()
        {
        }
        public void sendICall()
        {
        }

        public void returnValueHandler(int result)
        {

        }
    }

    internal class EventNotifier
    {
    }
}
