//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WxcmlParser.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


public class WxcmlParser {
	private List<WFelement> elements ;
	public void parse//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WFRunner.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

	
	protected class WFRunner : IReturnEvent, IReturnEvent, IReturnEvent{
		private List<WPFElement> elements ;
		public EventNotifier eventNotifier ;
		private void processElement(WFElement nextElem){
		}
		private void start(){
		}
		private void end(){
		}
		public void sendICall(){
		}
		public void returnValueHandler(int result){
		}
	}
