
//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WFRunner.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//


using System.Collections.Generic;
using RRComSSys.WorkflowEngine;

namespace RRComSSys.WorkflowEngine
{
    internal class WFRunner : IReturnEvent
    {
        private List<WFElement> elements;
        public EventNotifier eventNotifier;
        private void processElement(WFElement nextElem)
        {
        }
        private void start()
        {
        }
        private void end()
        {
        }
        public void sendICall()
        {
        }

        public void returnValueHandler(int result)
        {

        }
    }

    internal class EventNotifier
    {
    }
}
