//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : CommunicationCommand.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.SynthesisEngine;


public class CommunicationCommand extends Command {
}
