//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : CommandInvoker.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class CommandInvoker {
	public void invokeCommand(){
	}
}
