//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaParser.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.TransformationEngine;


public class SchemaParser extends Parser {
	public void validateSchema() {
	
	}
	
	public void notifyController() {
	
	}
}
