//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaView.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.TransformationEngine;


public class SchemaView implements ISchemaView {
	public SchemaController controller;

	@Override
	public void showForm() {
		// TODO Auto-generated method stub
		
	}
	
}
