//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : ActivityFactory.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

namespace RRComSSys.WorkflowEngine
{
    interface ActivityFactory
    {
        IActivity createActivity();
    }
}