//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Boundary.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

using System;
using RRComSSys.TransformationEngine;

namespace RRComSSys.WorkflowEngine
{
    public class Boundary :  WFElement
    {
        private TransformationEngine.Boundary myActivity=null;

        public Boundary( TransformationEngine.Boundary obj)
        {
            myActivity = obj;
        }    

        #region Overrides of WFElement


        public override bool processActivity()
        {
            return true; // For now....just step through the workflow
        }

        /// <summary>
        /// Gets the activity ID.
        /// </summary>
        /// <returns></returns>
        public override string getActivityID()
        {
            return myActivity.activityID;
        }

        public override string nextActivityID()
        {
            return myActivity.ToActivity;
        }

        public override Type TypeOfActivity()
        {
            return typeof (Boundary);
        }

        public bool Starts()
        {
            return myActivity.Type.Equals("Start");
        }

        public bool Ends()
        {
            return !Starts();
        }
        #endregion
    }

}
