//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Call.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//
namespace RRComSSys.WorkflowEngine
{
    public class Call : IActivity
    {
        #region Implementation of IActivity

        public bool processActivity()
        {
            return true;
        }

        #endregion
    }

} 


