//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : IActivity.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class IActivity {
	public object wxcml : data ;
	public void processActivity(){
	}
}
