//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : IReturnEvent.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public interface IReturnEvent : WFRunner {
}
