//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : IReturnEvent.cs
//  @ Date : 4/19/2009
//  @ Author : 
//
//

namespace RRComSSys.WorkflowEngine
{
    public interface IReturnEvent
    {
        void returnValueHandler(int result);
    }
}
