//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaView.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class SchemaView : ISchemaView{
	public SchemaController controller ;
}
