//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaModel.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class SchemaModel {
	public data schema ;
	public void updateSchema(){
	}
	public void saveInstance(){
	}
}
