//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaController.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class SchemaController {
	public ISchemaView view ;
	public void updateModel(){
	}
}
