//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : WGCMLToWXCMLParser.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class WGCMLToWXCMLParser : Parser{
	public void transformToWXCML(){
	}
}
