//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : CommAPIHandler.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class CommAPIHandler : SkypeAPIHandler{
	public IReturnEvent returnEvent ;
	public void addCommand(Command command){
	}
	public void send(){
	}
}
