//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Design Document
//  @ File Name : Command.cs
//  @ Date : 4/18/2009
//  @ Author : 
//
//


public class Command {
	public void Execute(){
	}
}
