//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : Rep_Data.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.Repository;


public class Rep_Data {
}
