//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : FileHandler.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//


package fiu.edu.TransformationEngine;


public class FileHandler {
	public void loadGCML() {
	
	}
	
	public void saveWXCML() {
	
	}
}
