//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : PipeStream.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//


package fiu.edu.TransformationEngine;

public class PipeStream {
	public void setInputBuffer() {
	
	}
	
	public void setOutputBuffer() {
	
	}
}
