//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaModel.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.TransformationEngine;


public class SchemaModel {
	//public data schema;
	public void updateSchema() {
	
	}
	
	public void saveInstance() {
	
	}
}
