//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : SchemaController.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.TransformationEngine;


public class SchemaController {
	public ISchemaView view;
	public void updateModel() {
	
	}
}
