//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : WGCMLToWXCMLParser.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.TransformationEngine;


public class WGCMLToWXCMLParser extends Parser {
	public void transformToWXCML() {
	
	}
}
