//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : Call.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.WorkflowEngine;


public class Call implements IActivity {

	@Override
	public void processActivity() {
		// TODO Auto-generated method stub
		
	}
}
