//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : IActivity.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.WorkflowEngine;


public interface IActivity {
	public Object wxcml = new Object();
	public void processActivity();
}
