//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Design Document
//  @ File Name : WxcmlParser.java
//  @ Date : 4/11/2009
//  @ Author : 
//
//

package fiu.edu.WorkflowEngine;

import java.util.ArrayList;


public class WxcmlParser {
	private ArrayList<WFElement> elements;
	public void parse(Object wxcml) {
	
	}
	
	private void addElement(ActivityFactory factory, Object elementData) {
	
	}
	
	public void execute() {
	
	}
}
